### ISSUE TITLE
Use comma instead of semicolon for flow types?

### ISSUE THREAD

**Issue by VictorChen** [ritz078/transform-www#12]
Instead of:

```
type Friends = {
  id: number;
  name: string;
}
```

can we have it generate:

```
type Friends = {
  id: number,
  name: string
}
```

(also, there should really be a semicolon after `type __ = {}`

FYI: https://flow.org/en/docs/types/aliases/

**Comment by ritz078** [comment]
Thanks for reporting. The fix is live now.

**Comment by VictorChen** [comment]
Thanks for the quick fix! There's another flow issue I've noticed, will track that in a new issue

**Comment by zirho** [comment]
do you know why it's dropping comma now?
![image](https://user-images.githubusercontent.com/1251296/140593612-9810002e-3415-49e6-b639-10f1b3164e7d.png)
