### ISSUE TITLE
JSON to Immutable prop types

### ISSUE THREAD

**Issue by Raathigesh** [ritz078/transform-www#14]
Should we do JSON to [Immutable prop types ](https://www.npmjs.com/package/react-immutable-proptypes)?

If yes, I would be happy to implement it!

**Comment by morajabi** [comment]
I think if @ritz078 would like to implement it, it is better for it to be a checkbox in *JSON to PropTypes* section.

**Comment by ritz078** [comment]
That would make more sense.

**Comment by Raathigesh** [comment]
Thanks! I'll give it a shot!

**Comment by ritz078** [comment]
@Raathigesh are you working on this ? Let me know if you are stuck somewhere.

**Comment by Raathigesh** [comment]
I really did not look into it yet. Planning to work on it during the
weekend.

**Comment by ritz078** [comment]
No problem.
