### ISSUE TITLE
Suggestion: I want to add JSON to GraphQL schema

### ISSUE THREAD

**Issue by morajabi** [ritz078/transform-www#7]
Hey @ritz078, awesome work here. I've been struggling with writing schemas for a couple of days recently and I know how it hurts 💯 

I just wanted to add two other functionality to this excellent project here. I want to contribute to this as long as I can. This is the first one, if you wish I can do that.

**Comment by ritz078** [comment]
That would be great. you can surely do a PR to start with.

**Comment by morajabi** [comment]
I will start soon, but before that can you tell me a bit how this project is structured exactly?

**Comment by ritz078** [comment]
AST is generated only for JSON to propTypes. Other than that, all transformations are string manipulations. 
to create a new route, create a file in pages folder `json-to-graphql.js` and add the route in Layout.js for navigation. each page uses the `ConversionPanel` component. you just pass the transformation function to that component. all the transformation functions are present inside `utils` folder.

**Comment by ritz078** [comment]
@morajabi I have already JSON to mongoose schema. You can work on GraphQL. Are you working on it ?

**Comment by morajabi** [comment]
@ritz078 Sorry, I was pretty busy. Glad to hear it, I'll do the GraphQL tomorrow is it OK?

**Comment by ritz078** [comment]
That will be great.

**Comment by morajabi** [comment]
Sorry, Where is the code for JSON to mongoose transformer? I couldn't find it.

**Comment by ritz078** [comment]
I am using a package for it .

https://github.com/nijikokun/generate-schema

Usage is here https://github.com/ritz078/transform-www/blob/master/pages/json-to-mongoose.js

**Comment by morajabi** [comment]
Sorry @ritz078, can you take a look [at my fork](https://github.com/morajabi/transform-www)? I don't know why it keeps getting longer on every re-render? I think it's a problem with the [package](https://github.com/aweary/json-to-graphql) I've used. If it is the problem and it can't be fixed, then I will find another way.

**Comment by ritz078** [comment]
It is an issue with the package.

**Comment by morajabi** [comment]
Oh, I see. So we have to make it on our own.

**Comment by ritz078** [comment]
Or just fork it and fix that issue.

**Comment by morajabi** [comment]
@ritz078 What exactly is the issue with that library?

**Comment by ritz078** [comment]
it seems they are pushing the output in an array and not clearing it on every call.

**Comment by ritz078** [comment]
I have used apollo-codegen and implemented it. Let me know what you think. I am still not sure about it.

https://transform.now.sh/graphql-to-typescript

**Comment by ritz078** [comment]
I have added you to the contributors list. https://github.com/ritz078/transform-www#contributors
